### ISSUE TITLE
Archived newsletters cannot be read

### ISSUE THREAD

**Issue by martinsrna** [nicholaschiang/hammock#31]
After opening a newsletter in the **Archive**, it goes back to **Archive** after 1-2 seconds:

![CleanShot 2021-05-12 at 11 45 10](https://user-images.githubusercontent.com/80906500/118028866-93d65a00-b331-11eb-99d6-d2f1691fb9b9.gif)

**Comment by nicholaschiang** [comment]
This is because of [this line of code](https://github.com/nicholaschiang/hammock/blob/develop/pages/messages/%5Bid%5D.tsx#L64) that redirects back if the message is archved:

```typescript
      if (updated.archived) Router.back();
```

Instead, I should only go back if the message was automatically archived because the user scrolled all the way down (and not if it was already archived). But, because that auto-archive feature is already disabled (for now), I can just get rid of all of that logic.
